# Generated by Django 2.2 on 2020-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Ice Diamond', max_length=100),
            preserve_default=False,
        ),
    ]
