# Generated by Django 2.2 on 2020-03-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
