# Generated by Django 2.2 on 2020-03-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('width', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('length', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('width', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('length', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
