# Generated by Django 2.2 on 2020-03-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200326_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingdimension',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='item_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='item_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='item_width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='package_height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.DeleteModel(
            name='ItemDimension',
        ),
        migrations.DeleteModel(
            name='PackagingDimension',
        ),
    ]
