# Generated by Django 2.2 on 2020-03-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line3',
            new_name='address_line_3',
        ),
    ]
