# Generated by Django 2.2 on 2020-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('mobile_image', models.ImageField(upload_to='images')),
                ('tablet_image', models.ImageField(upload_to='images')),
                ('desktop_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
